server.port=9090

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stats}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:stats}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:stats}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect